Python list have an array like representation. 

In [1]:
x = [1, 2, 3, 5, 9]

print(x * 2)

[1, 2, 3, 5, 9, 1, 2, 3, 5, 9]


In the above example, multiplying 2 with the list just doubles the list content. It does not do element wise calculation. To do so, we may use the map function or a loop or list comprehension.

In [5]:
print ("map: ", list (map(lambda n: n*2,  x )) )

print ("list comprehension: ", [n*2 for n in x] )

map:  [2, 4, 6, 10, 18]
list comprehension:  [2, 4, 6, 10, 18]


Now we will look into numpy array and see how it handles element-wise calculation

In [6]:
import numpy as np

In [7]:
x = np.array([1, 2, 3, 5, 9])
print (x *2)

[ 2  4  6 10 18]


Some of the key features provided by Numerical Python (numpy) library are:-
* Fast, space-efficient multidimentional array called ndarray
* Standard mathematical functions for fast operation on entire array without using loops
* Tools for reading/writing array data to disk
* Common array algorithms like sorting, unique, and set operations
* Matrix representation and linear algebra operations


Let's look at some of these functionality in more details

## ndarray
An ndarray is a multidimensional container for homogeneous data. All the elements must be the same type. Every array has a property called **shape** which is a tuple indicating the size of each dimension, and a property called **dtype** which is an object describing the data type of the array.

In [17]:
print("\n * 1D array *")
arr1D = np.array([ 11, 22, 33 ])
print(arr1D)

print("\n * 2D array * ")
arr2D = np.array([ [1,2,3], [4,5,6] ] )
print(arr2D)


 * 1D array *
[11 22 33]

 * 2D array * 
[[1 2 3]
 [4 5 6]]


The **array** function is used to create a NumPy array. It can convert input data, be it list, tuple, array, or other sequence type, to an ndarray.

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array. 

Now, let's create an array with a defined shape and data type

In [32]:
print("shape:{0} dtype:{1}".format(arr.shape, arr.dtype))

shape:(1, 12) dtype:float64


### Special arrays : empty, zeros and ones

In addition to the array function we have specialized functions to create arrays filled with 0's and 1's

We can pass an integer to specify the number of elements in the array 

In [44]:
# Create an array filled with 0's
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [43]:
# Create an array filled with 1's
np.ones(3)

array([ 1.,  1.,  1.])

We can create multidimentional versions of these arrays by specifying a **tuple** for the shape

For a 2D array, shape needs to be specified as (row x col)

In [42]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

We create an n-dimentional array using a shape tuple of the form ( n-instances , rows per instance, col per instance)

In [47]:
np.ones((2, 3, 4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

There are few more ways to create arrays

* empty()    : Return a new array of given shape and type, without initializing entries.
* identity() : Return the identity array.
* full()     : Return the identity array.
* eye()      : Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [52]:
# We create a 2x3 array filled with int value of 5 in each cell
np.full((2,3), 5, np.int32)

array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)

## NumPy Datatypes

The data type or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data. The numerical dtypes are named the same way: a **type name**, like float or int , followed by a number indicating the **number of bits per element**.

Example: **np.int32** for a 32bit integer, **np.float64** to represent a 64 bit floating point or **np.complex128** which would be a 128 bit complex floating-point number.

You can get more details at https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html

In [59]:
dt = np.dtype(float)   # Python-compatible floating-point number
print("Python-compatible floating-point number: ", dt)

dt = np.dtype(int)     # Python-compatible integer
print("Python-compatible integer: ", dt)

dt = np.dtype(object)  # Python object
print("Python object: ", dt)

dt = np.dtype('b')  # byte, native byte order
print("byte: ", dt)

dt = np.dtype('>H') # big-endian unsigned short
print("big-endian unsigned short: ", dt)

dt = np.dtype('<f') # little-endian single-precision float
print("little-endian single-precision float: ", dt)

dt = np.dtype('d')  # double-precision floating-point number
print("double-precision floating-point number: ", dt)

dt = np.dtype('uint32')   # 32-bit unsigned integer
print("32 bit unsigned int: ", dt)

dt = np.dtype('Float64')  # 64-bit floating-point number
print("64 bit floating-point number: ", dt)


Python-compatible floating-point number:  float64
Python-compatible integer:  int64
Python object:  object
byte:  int8
big-endian unsigned short:  >u2
little-endian single-precision float:  float32
double-precision floating-point number:  float64
32 bit unsigned int:  uint32
64 bit floating-point number:  float64


In [62]:
# Specifying datatype while creating array
arr = np.array([ [1,2,3], [4,5,6] ] , np.uint32)
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

We can explicitly convert or cast an array from one dtype to another using ndarray’s **astype** method

A TypeError will be raised in case the casting fails.

In [63]:
arr.astype(np.float32)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

## Vectorization

Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization. Any arithmetic operations between equal-size arrays applies the operation elementwise like we saw in the starting example.

In [71]:
arr = np.array([1, 2, 3, 5, 9])

# Scalar multiplication
dbl = arr *2
dbl

array([ 2,  4,  6, 10, 18])

In [69]:
# Creating a square by multiplying individual elements
sqr = arr * arr
sqr

array([ 1,  4,  9, 25, 81])

In [77]:
# We could have done this
arr ** 2

array([ 1,  4,  9, 25, 81])

In [72]:
dbl - arr

array([1, 2, 3, 5, 9])

In [73]:
sqr / arr

array([ 1.,  2.,  3.,  5.,  9.])

In [75]:
# Get the square root
sqr ** 0.5

array([ 1.,  2.,  3.,  5.,  9.])

In [78]:
1 / arr

array([ 1.        ,  0.5       ,  0.33333333,  0.2       ,  0.11111111])